#!/bin/bash

# This file is to wrap around the pipe.sh file provided in the repo and make sure that variables are all set for Github

## Convert GH to BB
export BITBUCKET_CLONE_DIR=$GITHUB_WORKSPACE
export BITBUCKET_BRANCH=${GITHUB_REF#refs/heads/}

## Inputs
export STEP=$INPUT_STEP
export CCV2_SUBSCRIPTION_ID=$INPUT_CCV2_SUBSCRIPTION_ID
export CCV2_API_KEY=$INPUT_CCV2_API_KEY
export CCV2_API_TIMEOUT=$INPUT_CCV2_API_TIMEOUT
export CCV2_API_REQUEST_SPACING=$INPUT_CCV2_API_REQUEST_SPACING
export SLACK_WEBHOOKS=$INPUT_SLACK_WEBHOOKS
export TEAMS_WEBHOOKS=$INPUT_TEAMS_WEBHOOKS
export JIRA_PREFIX=$INPUT_JIRA_PREFIX
export CCV2_DEPLOY_STRATEGY=$INPUT_CCV2_DEPLOY_STRATEGY
export SYSTEM_UPDATE_FILE_EXTENSIONS=$INPUT_SYSTEM_UPDATE_FILE_EXTENSIONS
export CCV2_BUILDS_LIMIT=$INPUT_CCV2_BUILDS_LIMIT
export CCV2_APPLICATION_CODE=$INPUT_CCV2_APPLICATION_CODE
export JMETER_TEST_TIMEOUT=$INPUT_JMETER_TEST_TIMEOUT
export DEBUG=$INPUT_DEBUG

## Environment Specific
export CCV2_ENVIRONMENT=$INPUT_CCV2_ENVIRONMENT
export JIRA_WEBHOOK=$INPUT_JIRA_WEBHOOK
export PATH_TO_ENVIRONMENT_PROPERTIES=$INPUT_PATH_TO_ENVIRONMENT_PROPERTIES
export VERSION_PROPERTY=$INPUT_VERSION_PROPERTY
export PRE_ALERT=$INPUT_PRE_ALERT
export JMETER_TEST_PACKAGE=$INPUT_JMETER_TEST_PACKAGE
export STATIC_FILES_CONFIG=$INPUT_STATIC_FILES_CONFIG
export REDIRECT_CONFIG=$INPUT_REDIRECT_CONFIG
export HOST_ALIAS_SET=$INPUT_HOST_ALIAS_SET
export FORCE_MIGRATION=$INPUT_FORCE_MIGRATION

. /pipe.sh