# action.yml
name: 'KPS CCv2 Action'
description: 'Call the CCv2 API'
inputs:
  step:
    description: 'Step'
    required: true
    default: 'BUILD'
  ccv2_environment:
    description: 'Environment To Act Upon'
    required: false
  ccv2_subscription_id:
    description: 'Subscription To Act Upon'
    required: true  
  ccv2_api_key:
    description: 'API Key for CCv2'
    required: true 
  ccv2_api_timeout :
    description: 'How long to wait for build/compile to finish (seconds)'
    required: false
    default: '1200'
  ccv2_api_request_spacing :
    description: 'Time between status calls to API (seconds)'
    required: false
    default: '30'
  slack_webhooks :
    description: 'Space-Separated list of Slack Webhooks to send alerts to  (optional)'
    required: false
  teams_webhooks :
    description: 'Space-Separated list of Teams Webhook to send alerts to (optional)'
    required: false
  jira_prefix :
    description: 'Prefix before ticket in Jira URL'
    required: false
  ccv2_deploy_strategy :
    description: 'Deployment Strategy. Possible options are ROLLING_UPDATE and RECREATE. (defaults to RECREATE)'
    required: false
    default: 'RECREATE'
  system_update_file_extensions :
    description: 'File extensions (suffixes) which, if altered, trigger a System Update. (defaults to items.xml, groovy and impex)'
    required: false
    default: '-items.xml,.groovy,.impex'
  ccv2_builds_limit :
    description: 'Limit the number of builds returned when looking for existing builds to deploy'
    required: false
    default: '30'
  ccv2_application_code :
    description: 'The application code within CCv2'
    required: false
    default: 'commerce-cloud'
  jmeter_test_timeout :
    description: 'The number of minutes to wait for test package to complete'
    required: false
    default: '1800'
  debug :
    description: 'Set to axios to debug connection to CCv2 (optional)'
    required: false
  jira_webhook:
    description: 'Webhook for Jira automation (optional)'
    required: false
  path_to_environment_properties:
    description: 'Path to environment specific properties (optional)'
    required: false
  version_property:
    description: 'The property which contains the version, this will be appended by the SAP build code'
    required: false
  pre_alert:
    description: 'Do you want an alert when the build starts as well as when the deployment starts?'
    required: false
  jmeter_test_package:
    description: 'The name of the JMeter test package in CCv2'
    required: false
  static_files_config:
    description: 'Path to properties file detailing static files'
    required: false
  redirect_config:
    description: 'Path to properties file detailing redirects'
    required: false
  host_alias_set:
    description: 'Path to host alias set'
    required: false
  force_migration:
    description: 'Should we system update regardless of file changes?'

runs:
  using: 'docker'
  image: 'Dockerfile'
