# action.yml
name: 'KPS CCv2 Action'
description: 'Call the CCv2 API'
inputs:
  step:
    description: 'Step'
    required: true
    default: 'BUILD'
  ccv2_environment:
    description: 'Environment To Act Upon'
    required: false
  ccv2_subscription_id:
    description: 'Subscription To Act Upon'
    required: true  
  ccv2_api_key:
    description: 'API Key for CCv2'
    required: true 
runs:
  using: 'docker'
  image: 'Dockerfile'
