# action.yml
name: 'Hello World'
description: 'Greet someone'
inputs:
  whotogreet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
