name: "CCv2 Deploy"
description: "Deploy to CCv2"
author: "KPS"
inputs:
  STEP:
    description: "The step to execute"
    required: true
  CCV2_ENVIRONMENT:
    description: "CCV2 environment identifier"
    required: true
  CCV2_SUBSCRIPTION_ID:
    description: "CCV2 subscription ID"
    required: true
  CCV2_API_KEY:
    description: "CCV2 API key"
    required: true
  CCV2_API_TIMEOUT:
    description: "Timeout for CCV2 API calls"
    required: false
  CCV2_API_REQUEST_SPACING:
    description: "Spacing between CCV2 API requests"
    required: false
  SLACK_WEBHOOKS:
    description: "Slack webhooks URL"
    required: false
  TEAMS_WEBHOOKS:
    description: "Teams webhooks URL"
    required: false
  JIRA_PREFIX:
    description: "Prefix for JIRA tasks"
    required: false
  CCV2_DEPLOY_STRATEGY:
    description: "CCV2 deployment strategy"
    required: false
  SYSTEM_UPDATE_FILE_EXTENSIONS:
    description: "File extensions for system updates"
    required: false
  CCV2_BUILDS_LIMIT:
    description: "Limit for CCV2 builds"
    required: false
  CCV2_APPLICATION_CODE:
    description: "Code for CCV2 application"
    required: false
  JIRA_WEBHOOK:
    description: "Webhook for JIRA integration"
    required: false
  PATH_TO_ENVIRONMENT_PROPERTIES:
    description: "Path to environment properties file"
    required: false
  BITBUCKET_USERNAME:
    description: "Bitbucket username"
    required: false
  BITBUCKET_APP_PASSWORD:
    description: "Bitbucket app password"
    required: false
  VERSION_PROPERTY:
    description: "Version property"
    required: false
  BUILD_NAME:
    description: "Name of the build"
    required: false
  PRE_ALERT:
    description: "Enable or disable pre-alert notifications"
    required: false
  FORCE_MIGRATION:
    description: "Force migration flag"
    required: false
  VERSION:
    description: "Version identifier"
    required: false
  JMETER_TEST_PACKAGE:
    description: "Package for JMeter tests"
    required: false
  JMETER_TEST_TIMEOUT:
    description: "Timeout for JMeter tests"
    required: false
  DEBUG:
    description: "Enable or disable debugging"
    required: false
  REDIRECT_CONFIG:
    description: "Configuration for redirects"
    required: false
  STATIC_FILES_CONFIG:
    description: "Configuration for static files"
    required: false
  SECURE_REPO_USERNAME:
    description: "Secure repository username"
    required: false
  SECURE_REPO_PASSWORD:
    description: "Secure repository password"
    required: false
  SECURE_REPO_SSH_KEY:
    description: "SSH key for secure repository"
    required: false
  GIT_DEFAULT_FROM_HASH:
    description: "Default Git hash to start from"
    required: false
  DEFAULT_UPDATE_MODE:
    description: "Default update mode"
    required: false
  SNAPSHOT_ENVIRONMENT:
    description: "Snapshot environment identifier"
    required: false
  SNAPSHOT_CUTOFF_DAYS:
    description: "Snapshot cutoff days"
    required: false
  TIDY_HOST_ALIAS_SETS:
    description: "Host alias sets for tidy"
    required: false
  USE_DEPLOYED_ANCESTOR:
    description: "Flag to use the deployed ancestor"
    required: false                  
runs:
  using: "docker"
  image: "europe-west1-docker.pkg.dev/envoydigital-hybris/bb-pipelines/ccv2-deployments/ccv2-deploy:2.4"
